config/routes.rb
Rails.application.routes.draw do

  devise_for :admin, skip: [:registrations, :passwords] , controllers: {
  sessions: "admin/sessions"
}
  devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  namespace :admin do
    resources :genres, only: [:index,:show,:edit,:create,:update]
    resources :items
    resources :customers, only:[:index,:show,:edit,:update]
    resources :orders, only: [:index, :show, :update] do
      resources :order_details, only: [:update]
    end
  end

  scope module: :public do
    get 'customers/unsubscribe', as: "unsubscribe"
    resources :customers, only: [:show, :edit, :update]
    resources :items, only: [:show, :index]
    delete 'cart_items/destroy_all', as: "destroy_all"
    resources :cart_items, only:[:index,:update,:destroy,:create]
    get 'orders/thanks', as: "thanks"
    post 'orders/confirm' => 'orders#confirm'
    resources :orders, only:[:index,:show,:new,:create]
    resources :addresses, only: [:index, :create, :edit, :update, :destroy]
    get 'about' => 'homes#about'
    root 'homes#top'
  end
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :genre
  
  has_many :post_images, dependent: :destroy
  has_many :order_items, dependent: :destroy
  
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  
  def index
    @items = Item.all
    @genres = Genre.all
  end

  def new
    @item = Item.new
    @genres = Genre.all
  end

  def create
    @item = Item.new(params_item)
    @item.save
    redirect_to admin_item_path(@item)
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
    @genres = Genre.all
  end
  
  def update
    @item = Item.find(params[:id])
    @item.update(params_item)
    redirect_to admin_item_path(@item)
  end

  private

  def params_item
    params.require(:item).permit(:name, :genre_id, :introduction, :price, :is_active)
  end

end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/views/admin/items/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-12">
      <%= form_with model: @item, url: admin_item_path(@item), method: :PUT do |f|%>
        <div>
        <div><%= f.label :商品名 %></div>
        <div><%= f.text_field :name%></div>
        </div>
        <div>
        <div><%= f.label :ジャンル %></div>
        <div><%= f.collection_select :genre_id,@genres, :id, :name, include_blank: "--選択してください--"%></div>
        </div>
        <div>
        <div><%= f.label :商品紹介 %></div>
        <div><%= f.text_area :introduction, size:"40" %></div>
        </div>
        <div>
        <div><%= f.label :価格 %></div>
        <div><%= f.text_field :price, placeholder: "1000" %>円</div>
        </div>
        <div>
        <div><%= f.label :販売状況 %></div>
        <div><%= f.check_box :is_active %></div>
        </div>
        <%= f.submit "更新" %>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/items/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-4">
      <% @genres.each do |genre| %>
      <button type="button" class="btn btn-outline-primary">
        <%= link_to admin_genre_path(genre) do %>
          <%= genre.name %>
        <% end %>
      </button>
      <% end %>
    </div>
    
    <div class="col-md-8">
      <div class="row">
      <% @items.each do |item| %>
        <div class="card-group">
          <div class="card">
            <div class="card-body">
              <h5 class="card-title"><%= link_to admin_item_path(item) do %><%= item.name %><% end %></h5>
              <p class="card-text"><%= item.introduction %></p>
              <p class="card-text"><small class="text-muted"><%= item.price%></small></p>
              <a href="#" class="btn btn-primary">Go somewhere</a>
            </div>
          </div>
        </div>
      <% end %>
      </div>
      <button type="button" class="btn btn-outline-primary">
        <%= link_to "新規登録", new_admin_item_path %>
      </button>
    </div>
  </div>
</div>

app/views/admin/items/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-8">
      <%= form_with model: @item, url: '/admin/items', method: :post do |f| %>
        <%= f.label :Name %>
        <%= f.text_field :name%>
        <%= f.label :genre %>
        <%= f.collection_select :genre_id,@genres, :id, :name, include_blank: "--選択してください--"%>
        <%= f.label :introduction %>
        <%= f.text_area :introduction%>
        <%= f.label :price %>
        <%= f.text_field :price, placeholder: "1000" %>円
        <%= f.label :is_active %>
        <%= f.check_box :is_active %>
        <%= f.submit "登録" %>
      <% end %>
    </div>
  </div> 
</div>

app/views/admin/items/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-6">
      <div>
        
      <p>商品名:<%= @item.name %></p>
      <p>商品説明:<%= @item.introduction %></p>
      <p>商品価格:<%= @item.price %>円</p>
      <p>販売状況:<%= @item.is_active %></p>
      <p>ジャンル:<%= @item.genre.name %></p>
      <button type="button" class="btn btn-outline-primary">
        <%= link_to "編集する",edit_admin_item_path(@item.id)%>
      </button>
      </div>
    </div>
  </div>
</div>