config/routes.rb
Rails.application.routes.draw do

  devise_for :admin, skip: [:registrations, :passwords] , controllers: {
  sessions: "admin/sessions"
}
  devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  namespace :admin do
    resources :genres, only: [:index,:show,:edit,:create,:update]
    resources :items
    resources :customers, only:[:index,:show,:edit,:update]
    resources :orders, only: [:index, :show, :update] do
      resources :order_details, only: [:update]
    end
  end

  scope module: :public do
    get 'customers/unsubscribe', as: "unsubscribe"
    resources :customers, only: [:show, :edit, :update]
    resources :items, only: [:show, :index]
    delete 'cart_items/destroy_all', as: "destroy_all"
    resources :cart_items, only:[:index,:update,:destroy,:create]
    get 'orders/thanks', as: "thanks"
    post 'orders/confirm' => 'orders#confirm'
    resources :orders, only:[:index,:show,:new,:create]
    resources :addresses, only: [:index, :create, :edit, :update, :destroy]
    get 'about' => 'homes#about'
    root 'homes#top'
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :cart_items, dependent: :destroy
  has_many :addresses, dependent: :destroy
  has_many :orders, dependent: :destroy
  
  enum prefectur:{
     "---":0,
     北海道:1,青森県:2,岩手県:3,宮城県:4,秋田県:5,山形県:6,福島県:7,
     茨城県:8,栃木県:9,群馬県:10,埼玉県:11,千葉県:12,東京都:13,神奈川県:14,
     新潟県:15,富山県:16,石川県:17,福井県:18,山梨県:19,長野県:20,
     岐阜県:21,静岡県:22,愛知県:23,三重県:24,
     滋賀県:25,京都府:26,大阪府:27,兵庫県:28,奈良県:29,和歌山県:30,
     鳥取県:31,島根県:32,岡山県:33,広島県:34,山口県:35,
     徳島県:36,香川県:37,愛媛県:38,高知県:39,
     福岡県:40,佐賀県:41,長崎県:42,熊本県:43,大分県:44,宮崎県:45,鹿児島県:46,
     沖縄県:47
   }
   
  
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  def index
    @customers = Customer.all
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end
  
  def update
    @customer = Customer.find(params[:id])
    if @customer.update(customer_params)
      redirect_to admin_customers_path
    else
      flash[:notice] = "入力内容を確認してください"
      render "edit"
    end
  end
  
  private
    def customer_params
      params.require(:customer).permit(:last_name, :first_name, :postal_code, :prefectur, :address, :phone_number, :is_deleted)
    end
  
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/views/admin/customers/edit.html.erb
<%= form_with(model: @customer, url: admin_customer_path, local: true ,method: :patch) do |f|%>
  <%= f.text_field :last_name %>
  <%= f.text_field :first_name %>
  <%= f.text_field :prefectur %>
  <%= f.text_field :address %>
  <%= f.text_field :phone_number %>
  <%= f.text_field :is_deleted  %>
  <%= f.submit "更新する" %>
<% end %>

app/views/admin/customers/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-12">
      
    </div>
  </div>
</div>
<table class="table table-dark">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">名前</th>
      <th scope="col">状態</th>
      <th scope="col">電話番号</th>
    </tr>
  </thead>
  <tbody>
    <% @customers.each do |customer|%>
    <tr>
      <th scope="row">1</th>
      <td>
        <%= link_to admin_customer_path(customer) do %>
          <div><%= customer.first_name %></div>
        <% end %>
      </td>
      <td><%= customer.is_deleted %></td>
      <td><%= customer.phone_number %></td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/customers/show.html.erb
<%= @customer.last_name %>
<%= @customer.first_name %>
<%= @customer.prefectur %>
<%= @customer.address %>
<%= @customer.phone_number %>
<%= @customer.is_deleted %>
<%= link_to "編集", edit_admin_customer_path(@customer)%>