config/routes.rb
Rails.application.routes.draw do

  devise_for :admin, skip: [:registrations, :passwords] , controllers: {
  sessions: "admin/sessions"
}
  devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  namespace :admin do
    resources :genres, only: [:index,:show,:edit,:create,:update]
    resources :items
    resources :customers, only:[:index,:show,:edit,:update]
    resources :orders, only: [:index, :show, :update] do
      resources :order_details, only: [:update]
    end
  end

  scope module: :public do
    get 'customers/unsubscribe', as: "unsubscribe"
    resources :customers, only: [:show, :edit, :update]
    resources :items, only: [:show, :index]
    delete 'cart_items/destroy_all', as: "destroy_all"
    resources :cart_items, only:[:index,:update,:destroy,:create]
    get 'orders/thanks', as: "thanks"
    post 'orders/confirm' => 'orders#confirm'
    resources :orders, only:[:index,:show,:new,:create]
    resources :addresses, only: [:index, :create, :edit, :update, :destroy]
    get 'about' => 'homes#about'
    root 'homes#top'
  end
end

app/models/genre.rb
class Genre < ApplicationRecord
  
  has_many :items
  
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  def index
    @genres = Genre.all.order(created_at: :desc)
    @genre = Genre.new
  end

  def create
    genre = Genre.new(genre_params)
    genre.save
    redirect_back(fallback_location: root_path)
  end

  def show
    @genre = Genre.find(params[:id])
    @genres = @genre.items
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    @genre.update(genre_params)
    redirect_to admin_genres_path
  end

  private

  def genre_params
    params.require(:genre).permit(:name)
  end

end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/views/admin/genres/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col">
      <%= form_with model: @genre, url: admin_genre_path do |f| %>
        <%= f.text_field :name %>
        <%=f.submit "更新" %>
      <% end %>
      <%= link_to "back", admin_genres_path %>
    </div>
  </div>
</div>

app/views/admin/genres/index.html.erb
<div class="container">
  <div class="row justify-content-between">
    <div class="col-sm-3">
      <h5>ジャンル新規作成</h5>
      <%= form_with model: @genre, url:admin_genres_path(@genre.id), method: :post do |f| %>
        <%= f.text_field :name, size: "16", placeholder: "食べ物" %>
        <%= f.submit "登録" %>
      <% end %>
    </div>
    <div class="col-sm-8">
      <table class="table table-dark">
        <thead>
          <tr>
            <th scope="col">ジャンル一覧</th>
          </tr>
        </thead>
        <tbody>
        <% @genres.each do |genre| %>
          <tr>
            <td><%= genre.name %></td>
            <td> <%= link_to  edit_admin_genre_path(genre) do %>
              <i class="fa-solid fa-pen-to-square"></i>編集
              <% end %>
            </td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/admin/genres/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-12">
      <% @genres.each do |genre| %>
        <%= link_to admin_item_path(genre) do %>
          <%= genre.name %>
        <% end %>
      <% end %>
    </div>
  </div>
</div>